### ISSUE TITLE
Remove Credentials 

### ISSUE THREAD

**Issue by Dminor7** [saksham49/MozScraper#1]
Hey,

While searching for moz scraper I came across your repo. In the code you have statically typed credentials for moz account. Please remove it. Save it as [environment](https://www.nylas.com/blog/making-use-of-environment-variables-in-python/) variables.

Thanks

**Comment by saksham49** [comment]
Hey,
Thank you so much for bringing this to my attention, it must've slipped my
mind. I'll do that ASAP!

**Comment by saksham49** [comment]
I have done the necessary, thank you so much for bringing it to my notice.
